language: node_js
node_js:
      - "6"
before_install:
  - "npm install -g https://$GITHUB_ACCESS_TOKEN@github.com/LucyBot-Inc/documentation-generator"
script:
  - ./scripts/build-and-commit.sh
notifications:
 email:
    recipients:
      - jess.portnoy@kaltura.com
      - bobby@lucybot.com
    on_success: change
    on_failure: always

